//30
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("1.4.0.30")]
[assembly: AssemblyVersion("1.4.0.0")]

namespace Kaboom
{
	public static class Version
	{
		public const int major = 1;
		public const int minor = 4;
		public const int patch = 0;
		public const int build = 0;
		public const string Number = "1.4.0.0";
#if DEBUG
		public const string Text = Number + " DEBUG";
#else
		public const string Text = Number + "";
#endif
	}
}