//24
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("1.3.99.24")]
[assembly: AssemblyVersion("1.3.99.2")]

namespace Kaboom
{
	public static class Version
	{
		public const int major = 1;
		public const int minor = 3;
		public const int patch = 99;
		public const int build = 2;
		public const string Number = "1.3.99.2";
#if DEBUG
		public const string Text = Number + " DEBUG";
#else
		public const string Text = Number + "";
#endif
	}
}